# Python Basic Libraries: Statistics, Math, Numpy, and Scipy

This notebook demonstrates usage of basic Python libraries and methods, including math operations, numpy arrays, and linear algebra functions from scipy.


In [11]:
import math
import statistics
import numpy as np
from scipy import linalg

# a) Usage of math methods
print("floor(8.9):", math.floor(8.9))      # 3
print("ceil(3.3):", math.ceil(3.3))        # 4
print("sqrt(16):", math.sqrt(16))          # 4.0
print("isqrt(16):", math.isqrt(16))        # 4 (integer sqrt)
print("gcd(12, 15):", math.gcd(12, 15))    # 3


floor(8.9): 8
ceil(3.3): 4
sqrt(16): 4.0
isqrt(16): 4
gcd(12, 15): 3


- `floor()`: Returns the greatest integer less than or equal to a given number.
- `ceil()`: Returns the smallest integer greater than or equal to a given number.
- `sqrt()`: Calculates the square root (float result).
- `isqrt()`: Calculates the integer square root.
- `gcd()`: Returns the greatest common divisor of two numbers.


In [2]:
# b) Numpy array attributes and methods
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("ndim:", arr.ndim)       # Number of dimensions
print("shape:", arr.shape)     # Shape of the array
print("size:", arr.size)       # Total elements
print("sum:", arr.sum())       # Sum of all elements
print("mean:", arr.mean())     # Mean value
print("Sorted array:", np.sort(arr, axis=None))  # Flatten and sort
print("Sin of array:\n", np.sin(arr))            # Element-wise sine


Array:
 [[1 2 3]
 [4 5 6]]
ndim: 2
shape: (2, 3)
size: 6
sum: 21
mean: 3.5
Sorted array: [1 2 3 4 5 6]
Sin of array:
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


- `ndim`: Number of dimensions of the array.
- `shape`: Tuple representing the size of the array in each dimension.
- `size`: Total number of elements in the array.
- `sum()`: Sum of all elements.
- `mean()`: Average of the elements.
- `sort()`: Sorts elements.
- `sin()`: Computes the sine of each element (element-wise).


In [3]:
# c) Using scipy.linalg for determinant and eigenvalues
matrix = np.array([[4, 2], [3, 1]])
det = linalg.det(matrix)
eigvals, eigvecs = linalg.eig(matrix)
print("Matrix:\n", matrix)
print("Determinant:", det)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)


Matrix:
 [[4 2]
 [3 1]]
Determinant: -2.0
Eigenvalues: [ 5.37228132+0.j -0.37228132+0.j]
Eigenvectors:
 [[ 0.82456484 -0.41597356]
 [ 0.56576746  0.90937671]]


- `det()`: Computes the determinant of a matrix.
- `eig()`: Computes eigenvalues and eigenvectors of a square matrix.


In [4]:
# d) Reshaping 1D list into 2D and 3D matrices using numpy
lst = list(range(1, 13))  # 1D list with 12 elements
arr_1d = np.array(lst)
arr_2d = arr_1d.reshape(3, 4)   # 3 rows, 4 columns
arr_3d = arr_1d.reshape(2, 2, 3) # 3D matrix: 2x2x3
print("1D array:", arr_1d)
print("2D array:\n", arr_2d)
print("3D array:\n", arr_3d)


1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3D array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


- `reshape()`: Changes the shape of the array without changing its data.
- The product of dimensions must remain the same (e.g., 12 elements reshaped into 3x4 or 2x2x3).


In [5]:
# e) Generate random matrices using numpy
rand_matrix = np.random.rand(3, 3)   # 3x3 matrix with random floats [0,1)
print("Random matrix:\n", rand_matrix)


Random matrix:
 [[0.26655067 0.27083153 0.35851931]
 [0.31165934 0.74960585 0.49370499]
 [0.10144116 0.87918548 0.96028531]]


In [6]:
# f) Find determinant using scipy
det_rand = linalg.det(rand_matrix)
print("Determinant of random matrix:", det_rand)




Determinant of random matrix: 0.07965737647031806


In [7]:
# g) Find eigenvalues and eigenvectors using scipy
eigvals_rand, eigvecs_rand = linalg.eig(rand_matrix)
print("Eigenvalues:\n", eigvals_rand)
print("Eigenvectors:\n", eigvecs_rand)

Eigenvalues:
 [1.62449266+0.j         0.17597459+0.13441792j 0.17597459-0.13441792j]
Eigenvectors:
 [[ 0.31400059+0.j         -0.03968864-0.52631666j -0.03968864+0.52631666j]
 [ 0.54897668+0.j         -0.55320376+0.15632168j -0.55320376-0.15632168j]
 [ 0.7746149 +0.j          0.62525572+0.j          0.62525572-0.j        ]]


We have explored basic math functions, numpy array properties, reshaping arrays, and used scipy for determinant and eigen computations. These are foundational tools for scientific computing in Python.
