In [ ]:
import pandas as pd

# Create a simple dataset
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 30, 22],
    'City': ['Chennai', 'Madurai', 'Trichy']
}
df = pd.DataFrame(data)
print("Created Dataset:\n", df)


Created Dataset:
       Name  Age     City
0    Alice   24  Chennai
1      Bob   30  Madurai
2  Charlie   22   Trichy


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving csvfile.csv to csvfile.csv


In [ ]:
import pandas as pd
df = pd.read_csv("csvfile.csv")
print(df.head())


     Name  Age  Marks
0  Janani   20     99
1  Suriya   20    100


In [ ]:
import numpy as np
from scipy import stats

data = [12, 18, 25, 25, 30, 30, 30, 35, 40, 50]
arr = np.array(data)

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Mode:", stats.mode(arr, keepdims=True).mode[0])
print("Variance:", np.var(arr))
print("Standard Deviation:", np.std(arr))


Mean: 29.5
Median: 30.0
Mode: 30
Variance: 104.05
Standard Deviation: 10.200490184299968


In [ ]:
arr = np.arange(1, 13)
print("Original 1D Array:", arr)
reshaped = arr.reshape(3, 4)
print("Reshaped 3x4 Array:\n", reshaped)


Original 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
df = pd.DataFrame({'Name': ['A', 'B', 'C'], 'Marks': [85, 60, 95]})
filtered = df[df['Marks'] > 70]
print("Filtered Data:\n", filtered)


Filtered Data:
   Name  Marks
0    A     85
2    C     95


In [ ]:
df1 = pd.DataFrame({'ID': [1, 2], 'Name': ['A', 'B']})
df2 = pd.DataFrame({'ID': [1, 2], 'City': ['Chennai', 'Madurai']})
merged = pd.merge(df1, df2, on='ID')
print("Merged Data:\n", merged)


Merged Data:
    ID Name     City
0   1    A  Chennai
1   2    B  Madurai


In [ ]:
df = pd.DataFrame({
    'Name': ['A', 'B', 'C'],
    'Age': [25, None, 30],
    'Marks': [85, 90, None]
})
print("Original Data:\n", df)
df_filled = df.fillna(df.mean(numeric_only=True))
print("After Handling Missing Values:\n", df_filled)


Original Data:
   Name   Age  Marks
0    A  25.0   85.0
1    B   NaN   90.0
2    C  30.0    NaN
After Handling Missing Values:
   Name   Age  Marks
0    A  25.0   85.0
1    B  27.5   90.0
2    C  30.0   87.5


In [ ]:
from sklearn.preprocessing import MinMaxScaler

df = pd.DataFrame({'Age': [20, 25, 30, 35], 'Marks': [50, 60, 80, 90]})
scaler = MinMaxScaler()
df[['Age', 'Marks']] = scaler.fit_transform(df[['Age', 'Marks']])
print("After Min-Max Normalization:\n", df)


After Min-Max Normalization:
         Age  Marks
0  0.000000   0.00
1  0.333333   0.25
2  0.666667   0.75
3  1.000000   1.00
