In [2]:
import math

print("The Ceil of 3.2 is :",math.ceil(3.2))
print("The Floor of 3.2 is :",math.floor(3.2))
print("The Square Root of 9 is :",math.sqrt(9))
print("The Interger Square Root of 3.2 is :",math.isqrt(9))
print("The GCD of 3 and 9 is :",math.gcd(3,9))
print("6C4 is :",math.comb(6,4))
print("6P4 is :",math.perm(6,4))
print("Log of 10 base 10 is :",math.log(10,10))

The Ceil of 3.2 is : 4
The Floor of 3.2 is : 3
The Square Root of 9 is : 3.0
The Interger Square Root of 3.2 is : 3
The GCD of 3 and 9 is : 3
6C4 is : 15
6P4 is : 360
Log of 10 base 10 is : 1.0


In [21]:
import pandas as pd

data={"Subjects":["CN","CD","ML","WP","ADBMS"]}
df=pd.DataFrame(data)
print(df)

print("\nThe Contents of the CSV file is :")
csv_file=pd.read_csv("Sample.csv")
print(csv_file)

from sklearn import datasets
print("\nThe Iris dataset :")
iris=datasets.load_iris()
print(iris.data)

  Subjects
0       CN
1       CD
2       ML
3       WP
4    ADBMS

The Contents of the CSV file is :
   Food ID   Food Item  Price
0        1       Sushi   3.99
1        2     Burrito   9.99
2        3        Taco   2.99
3        4  Quesadilla   4.25
4        5       Pizza   2.49
5        6       Pasta  13.99
6        7       Steak  24.99
7        8       Salad  11.25
8        9       Donut   0.99
9       10       Drink   1.75

The Iris dataset :
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [15]:
import numpy as np
import statistics as st

arr=np.array([44,23,67,89,12,45])
print("Mean :",st.mean(arr))
print("Mean :",np.mean(arr))
print("Median :",st.median(arr))
print("Median :",np.median(arr))
print("Mode :",st.mode(arr))
print("Variance :",np.var(arr))
# print("Standard deviation :",st.stdev(arr))
print("Standard deviation :",np.std(arr))

Mean : 46
Mean : 46.666666666666664
Median : 44.5
Median : 44.5
Mode : 44
Variance : 662.8888888888889
Standard deviation : 25.746628689770024
