In [1]:
import math

print("Floor of 3.2 is ",math.floor(3.2))
print("Ceil of 3.2 is ",math.ceil(3.2))
print("Square root of 4 is ",math.sqrt(4))
print("Integer Square root of 4 is ",math.isqrt(4))
print("GCD of 3 and 2 is ",math.gcd(3,2))

Floor of 3.2 is  3
Ceil of 3.2 is  4
Square root of 4 is  2.0
Integer Square root of 4 is  2
GCD of 3 and 2 is  1


In [ ]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6],[8,7,9]])

print("Dimensions :",arr.ndim)
print("Shape :",arr.shape)
print("Size :",arr.size)
print("Sum of elements :",arr.sum())
print("Sum of elements :",sum(arr)) #sum of elements of the column
print("Mean of the array :",arr.mean())
print("Original array :\n",arr)
print("Sorted array :\n",np.sort(arr))
print("Sine of the array :\n",np.sin(arr))

Dimensions : 2
Shape : (3, 3)
Size : 9
Sum of elements : 45
Sum of elements : [13 14 18]
Mean of the array : 5.0
Original array :
 [[1 2 3]
 [4 5 6]
 [8 7 9]]
Sorted array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sine of the array :
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.98935825  0.6569866   0.41211849]]


In [ ]:
matrix=np.array([[1,2],[7,8]])

det_val=np.linalg.det(matrix)

print("The Determinant of the matrix is :",det_val)

eig_val,eig_vector=np.linalg.eig(matrix)

print("Eigen Value :",eig_val)
print("Eigen Vector :\n",eig_vector)

The Determinant of the matrix is : -6.0
Eigen Value : [-0.62347538  9.62347538]
Eigen Vector :
 [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]


In [ ]:
list=[i for i in range(1,13)]

array1D=np.array(list)
array2D=array1D.reshape(4,3)
array3D=array1D.reshape(2,2,3)

print("List :",list)
print("1D array :",array1D)
print("2D array :\n",array2D)
print("3D array :\n",array3D)

List : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
1D array : [ 1  2  3  4  5  6  7  8  9 10 11 12]
2D array :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
3D array :
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
zero_mat=np.zeros((3,3))
ones_mat=np.ones((3,3))
random_mat=np.random.rand(3,3)
identity_mat=np.eye(3)

print("Zero matrix :\n",zero_mat)
print("Ones matrix :\n",ones_mat)
print("Random matrix :\n",random_mat)
print("Identity matrix :\n",identity_mat)

Zero matrix :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones matrix :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Random matrix :
 [[0.60041934 0.93366753 0.15365914]
 [0.9268315  0.04661355 0.75350136]
 [0.2460073  0.71516288 0.00131911]]
Identity matrix :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
from scipy.linalg import det

arr=np.array([[1,0,0],[1,1,0],[0,0,0]])
det_val=det(arr)
print("The determinant of the array is :",det_val)

The determinant of the array is : 0.0


In [ ]:
from scipy.linalg import eig
matrix=np.array([[1,2],[7,8]])
eig_val,eig_vector=eig(matrix)

print("Eigen Value :",eig_val)
print("Eigen Vector :\n",eig_vector)

Eigen Value : [-0.62347538+0.j  9.62347538+0.j]
Eigen Vector :
 [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]


In [ ]:
import pandas as pd

data=pd.Series([i for i in range(1,11)])

print("The series is :\n",data)

The series is :
 0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64


In [ ]:
print("Index :",data.index)
print("Values :",data.values)

Index : RangeIndex(start=0, stop=10, step=1)
Values : [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print("Numpy array :",arr)
print("Pandas Series :\n",data)

Numpy array : [[1 0 0]
 [1 1 0]
 [0 0 0]]
Pandas Series :
 0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64


In [ ]:
data=pd.Series([100,99,97,96,100],index=["Tamil","English","Maths","Science","Social Science"])
print(data)

Tamil             100
English            99
Maths              97
Science            96
Social Science    100
dtype: int64


In [ ]:
print("Tamil Mark :",data["Tamil"])

Tamil Mark : 100
